#!/usr/bin/env bash

echo "running python simple server..."
python -m SimpleHTTPServer

# echo "starting Chrome..."
# /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome "http://localhost:8000"